weblog/blog/urls.py
from django.urls import path
from .views import home , detial ,category

app_name = "blog"
urlpatterns = [
    path('',home,name='home'),
    path('article/<slug:slug>',detial,name='detial'),  
    path('category/<slug:slug>',category , name="category")
     
]

weblog/weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
   
    
    
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

weblog/blog/models.py
from django.db import models
from django.utils import timezone
from extensions.utils import jalali_converter

class ArticleManager(models.Manager):
       def published(self):
              return self.filter(status = "p")

class Category(models.Model):
       parent = models.ForeignKey('self',default=None,null=True,blank=True,on_delete=models.SET_NULL,related_name="children",verbose_name='زیردسته')
       title = models.CharField(max_length=200, verbose_name="دسته بندی مقالات")
       slug=models.SlugField(max_length=200,unique=True,verbose_name="آدرس دسته بندی ها")
       status = models.BooleanField(default=True,verbose_name="آیا نمایش داده شود؟")
       position = models.IntegerField(verbose_name="موقعیت")
       
       class Meta:
         verbose_name = "دسته بندی"
         verbose_name_plural = "دسته بندی ها"
         ordering = ['parent__id','position']
         
       def __str__(self):
           return self.title

# Create your models here for Article table.
class Article(models.Model):
    STATUS_CHOICES =( 
           ('d','پیش نویس'),
           ('p','منتشر شده')           
    )
    titie = models.CharField(max_length=200 , verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length=100,unique=True,verbose_name="آدرس مقاله")
    category = models.ManyToManyField(Category,verbose_name="دسته بندی",related_name="articles")
    description = models.TextField(verbose_name="توضیحات")
    thumbnail = models.ImageField(upload_to="images",verbose_name="عکس")
    publish = models.DateTimeField(default=timezone.now,verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=STATUS_CHOICES,verbose_name="وضعیت")
    class Meta:
         verbose_name = "مقاله"
         verbose_name_plural = "مقالات"
         ordering = ['-publish']
         
         
    def __str__(self):  #for show the title name in the table in admin pannel
           return self.titie
    
    def jpublish(self):
           return jalali_converter(self.publish)
    jpublish.short_description ="زمان انتشار"
    
    def category_published(self):
           return self.category.filter(status = True)
    
    objects = ArticleManager() 

weblog/blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Article,Category
from django.core.paginator import Paginator


def home(request):
    article_list = Article.objects.published()
    paginator = Paginator(article_list, 4)
    page_number = request.GET.get('p')
    articles = paginator.get_page(page_number)
    
    context = {            # we can get data from database with model
        "articles": articles,
        # "category":  Category.objects.filter(status=True)
    }
    return render(request, "blog/home.html", context)


def detial(request, slug):
    context = {            # we can get data from database with model
        # "article":  Article.objects.get(slug=slug)
        # صفحه 404 و پستهایی که پابلیش شدند نمایش داده می شوند
        "article":  get_object_or_404(Article.objects.published(), slug=slug),
        # "category":  Category.objects.filter(status=True)
    }
    return render(request, "blog/detail.html", context)

def category(request,slug):
    context={
        "category": get_object_or_404(Category, slug=slug ,status = True )
    }
    return render(request,"blog/category.html",context)

weblog/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block main %}
{% load static %}
     <!-- Page Header-->
     <header class="masthead" style="background-image: url("{% static 'blog/assets/img/home-bg.jpg' %}")">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Clean Blog</h1>
                        <span class="subheading">A Blog Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
 <!-- Main Content-->
 <main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
        </div>
    </div>
</main>
{% endblock main %}

weblog/blog/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
    <head >
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>صفحه رسمی فرهاد کریم زاده {% block titie %}{% endblock titie %}</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static  'blog/css/styles.css'  %}" rel="stylesheet" />
        <link href="{% static  'blog/css/rtl.css'  %}" rel="stylesheet" />
    </head>
    
    <body style="background-color:rgb(73,66,108)">
        <!-- Navigation-->
        <nav   class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">

                <a class="navbar-brand" href="{% url 'blog:home' %}" style="color:rgb(240,194,142)"> {% title  %} </a>
                {% comment %} navbar here {% endcomment %}

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                
                {% category_navbar %}

            </div>
        </nav>
        
        <!-- Main Content-->
        {% block main %}
        
        {% endblock main %}
        <!-- Footer-->
        <footer class="border-top" style="background-color: rgb(55,51,88)">
            <div class="container px-4 px-lg-5" >
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Farhad Karimzadeh</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'blog/js/scripts.js' %}"></script>
    </body>
</html>

weblog/blog/templates/blog/category.html
   
   {% extends 'blog/base.html' %}
   {% block main %}
{% load static %}
        <!-- Page Header-->
        {% comment %} <div style="background-color:rgb(51,53,74)"> {% endcomment %}
        <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}');
                                border-radius:0px 0px 20% 20%">
            <div class="container position-relative px-4 px-lg-5" >
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading" style="font-family:IRANSans;font-size:50">
                            <h1>فرهاد کریم زاده</h1>
                            {% comment %} <span class="subheading">A Blog Theme by Start Bootstrap</span> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% comment %} </div> {% endcomment %}
   <!-- Main Content-->
   <div class="container px-4 px-lg-5" >
    <div class="row gx-4 gx-lg-5 justify-content-center" >
        
        <div class="col-md-10 col-lg-8 col-xl-7" >
            <h3 style="background-color: rgb(55,51,88);
                    color:rgb(240,194,142);
                    border-radius: 30%;
                    padding:15px 50px 15px 50px; 
                    margin:20px 0px 10px 0px ;
                    box-shadow: 0px 0px 15px #888888;
                    text-align:center;
                    font-size:20px;
                    font-family:IRANSans;
                    justify-content: space-between"> دسته بندی:  {{ category.title }}</h3>

            {% for article in category.articles.published %}

            <!-- Post preview-->
            <div class="post-preview" style="background-color: rgb(55,51,88);
                                             border-radius: 50% 20% / 10% 40%;
                                             padding:1px 50px 5px 50px; 
                                             margin:20px 0px 10px 0px ;
                                             box-shadow: 5px 5px 15px;
                                             justify-content: space-between">
                <a href="{% url 'blog:detial' article.slug %}">
                    <h2 class="post-title" style = "color: rgb(65,123,233);font-size:25px;font-family:IRANSans">{{ article.titie }}</h2>
                    <h4 class="post-subtitle" style = "color: rgb(144,175,232)">{{ article.description | truncatewords:10 }}</h4>
                </a>
                  
                <p class="post-meta" style = "color: rgb(107,114,218)">
                    نوشته ی
                    <span> فرهاد</span>
                {{article.jpublish}}
                
                </p>
                <div  style = "margin-bottom:20px">
                    <span class="badge rounded-pill bg-secondary" style = "font-size : 12px">
                    {%for cat in article.category_published%}
                   <a href="{% url 'blog:category' cat.slug %}"> {{cat.title}}</a>
                    {% endfor%}
                </span>
            </div>         
           
      
            </div>
            
            {% endfor %} 
            <!-- Pager-->
            <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!"  style = "background-color: rgb(240,194,142);
                                                                                                                        color:rgb(55,51,88);
                                                                                                                        border-radius: 50% 20% / 10% 40% ;
                                                                                                                        box-shadow: 5px 5px 5px ;
                                                                                                                        margin:20px 0px 10px 0px ">پستهای قدیمی  &larr;</a></div>
        </div>
    </div>
</div>

{% endblock main %}

weblog/blog/templates/blog/contact.html
        {% extends 'blog/base.html' %}
        {% block main %}
        {% load static %}
             <!-- Page Header-->
             <header class="masthead" style="background-image: url("{% static 'blog/assets/img/home-bg.jpg' %}")">
                <div class="container position-relative px-4 px-lg-5">
                    <div class="row gx-4 gx-lg-5 justify-content-center">
                        <div class="col-md-10 col-lg-8 col-xl-7">
                            <div class="site-heading">
                                <h1>Clean Blog</h1>
                                <span class="subheading">A Blog Theme by Start Bootstrap</span>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
        <!-- Main Content-->
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <div class="form-floating">
                                    <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        {% endblock main %}

weblog/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block titie %} | {{article.titie}} {% endblock titie %}
{% block main %}
{% load static %}

     <!-- Page Header-->
     <header class="masthead" style="background-image: url('{{ article.thumbnail.url }}');border-radius:0px 0px 20% 20%;">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>{{article.titie}}</h1>
                        <time>{{article.jpublish}}</time>
                        <span class="subheading">
                           
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
       <!-- Post Content-->
       <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7" style = "color:rgb(240,194,142);text-align: justify">
                    {{article.description | linebreaks}}
                </div>
                
            </div>
        </div>
    </article>
{% endblock main %}

weblog/blog/templates/blog/home.html
   
   {% extends 'blog/base.html' %}
   {% block main %}
{% load static %}
        <!-- Page Header-->
        {% comment %} <div style="background-color:rgb(51,53,74)"> {% endcomment %}
        <header class="masthead" style="background-image: url('{% static "blog/assets/img/home-bg.jpg" %}');
                                border-radius:0px 0px 20% 20%">
            <div class="container position-relative px-4 px-lg-5" >
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading" >
                            <h1>فرهاد کریم زاده</h1>
                            {% comment %} <span class="subheading">A Blog Theme by Start Bootstrap</span> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% comment %} </div> {% endcomment %}
   <!-- Main Content-->
   <div class="container px-4 px-lg-5" >
    <div class="row gx-4 gx-lg-5 justify-content-center" >
        <div class="col-md-10 col-lg-8 col-xl-7" >

            {% for article in articles %}

            <!-- Post preview-->
            <div class="post-preview" style="background-color: rgb(55,51,88);
                                             border-radius: 50% 20% / 10% 40%;
                                             padding:1px 50px 5px 50px; 
                                             margin:20px 0px 10px 0px ;
                                             box-shadow: 5px 5px 15px;
                                            
                                             justify-content: space-between">
                <a href="{% url 'blog:detial' article.slug %}">
                    <h2 class="post-title" style = "color: rgb(65,123,233);font-size:25px;font-family:IRANSans">{{ article.titie }}</h2>
                    <h4 class="post-subtitle" style = "color: rgb(144,175,232)">{{ article.description | truncatewords:10 }}</h4>
                </a>
                  
                <p class="post-meta" style = "color: rgb(107,114,218)">
                    نوشته ی
                    <span> فرهاد</span>
                {{article.jpublish}}
                
                </p>
                <div  style = "margin-bottom:20px ;  font-size:15px">
                    <span class="badge rounded-pill bg-secondary text-left">
                         {%for cat in article.category_published%}
                         {% comment %} "{% url 'blog:category' cat.slug  %}" {% endcomment %}
                           <a href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>
                         {% endfor%}
                    </span>
                </div>         
           
      
            </div>
           
            <!-- Divider-->
            {% comment %} <hr class="my-4" /> {% endcomment %}
 
            {% endfor %} 
            <!-- Pager-->
           {%if articles.has_previous%}
           

           <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home'%}?p={{articles.previous_page_number}}"  style = "background-color: rgb(240,194,142);
            color:rgb(55,51,88);
            border-radius: 50% 20% / 10% 40% ;
            box-shadow: 5px 5px 5px ;
            margin:20px 0px 10px 0px ">پستهای قدیمی  &larr;</a></div>  

           {%endif%}
           {%if articles.has_next%}
           

           <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="{% url 'blog:home'%}?p={{articles.next_page_number}}"  style = "background-color: rgb(240,194,142);
            color:rgb(55,51,88);
            border-radius: 50% 20% / 10% 40% ;
            box-shadow: 5px 5px 5px ;
            margin:20px 0px 10px 0px ">پستهای جدید  &rarr;</a></div>  

           {%endif%}
      
      
                                                                                                                                                                                                                                   </div>
    </div>
</div>

{% endblock main %}

weblog/blog/templates/blog/partials/category_navbar.html
<div class="collapse navbar-collapse" id="navbarResponsive" >
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:home' %}"style="color:rgb(240,194,142)">خانه</a></li>
            {% for cat in category%}
         <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:category' cat.slug  %}"style="color:rgb(240,194,142)">{{ cat.title }}</a></li>
            {% endfor %}
    </ul>
</div>